name: pazartesi_basliyorum
description: Alışkanlık takip uygulaması - Pazartesi Başlıyorum
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cached_network_image: ^3.3.1
  cloud_firestore: ^4.17.3
  connectivity_plus: ^6.0.3
  cupertino_icons: ^1.0.8
  equatable: ^2.0.5
  firebase_auth: ^4.19.4
  firebase_core: ^2.31.0
  firebase_messaging: ^14.9.2
  firebase_storage: ^11.7.4
  fl_chart: ^0.68.0
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  flutter_slidable: ^3.1.0
  freezed_annotation: ^2.4.1
  google_sign_in: ^6.2.1
  image_picker: ^1.1.2
  intl: ^0.20.2
  json_annotation: ^4.9.0
  riverpod_annotation: ^2.3.5
  share_plus: ^9.0.0
  shared_preferences: ^2.2.3
  shimmer: ^3.0.0
  table_calendar: ^3.1.1
  uuid: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  mockito: ^5.4.4
  riverpod_generator: ^2.4.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/icons/