// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
            'DefaultFirebaseOptions have not been configured for linux');
      default:
        throw UnsupportedError(
            'DefaultFirebaseOptions are not supported for this platform.');
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBE1M2mBAs6CzyCeRFkIQaIW5r_Mg7-vKo',
    appId: '1:863421991859:web:abcdef123456',
    messagingSenderId: '863421991859',
    projectId: 'pazartesi-basliyorum',
    authDomain: 'pazartesi-basliyorum.firebaseapp.com',
    storageBucket: 'pazartesi-basliyorum.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBE1M2mBAs6CzyCeRFkIQaIW5r_Mg7-vKo',
    appId: '1:863421991859:android:8b3fa41d6e5c9f2a2e7b1c',
    messagingSenderId: '863421991859',
    projectId: 'pazartesi-basliyorum',
    storageBucket: 'pazartesi-basliyorum.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBE1M2mBAs6CzyCeRFkIQaIW5r_Mg7-vKo',
    appId: '1:863421991859:ios:abcdef123456',
    messagingSenderId: '863421991859',
    projectId: 'pazartesi-basliyorum',
    storageBucket: 'pazartesi-basliyorum.firebasestorage.app',
    iosBundleId: 'com.loncagames.pazartesibasliyorum',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBE1M2mBAs6CzyCeRFkIQaIW5r_Mg7-vKo',
    appId: '1:863421991859:ios:abcdef123456',
    messagingSenderId: '863421991859',
    projectId: 'pazartesi-basliyorum',
    storageBucket: 'pazartesi-basliyorum.firebasestorage.app',
    iosBundleId: 'com.loncagames.pazartesibasliyorum',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBE1M2mBAs6CzyCeRFkIQaIW5r_Mg7-vKo',
    appId: '1:863421991859:web:abcdef123456',
    messagingSenderId: '863421991859',
    projectId: 'pazartesi-basliyorum',
    authDomain: 'pazartesi-basliyorum.firebaseapp.com',
    storageBucket: 'pazartesi-basliyorum.firebasestorage.app',
  );
}
